name: flutter_box_transform
description: A Flutter implementation of rect_resizer package.

version: 0.1.0

repository: https://github.com/BirjuVachhani/box_transform
homepage: https://github.com/BirjuVachhani/box_transform
issue_tracker: https://github.com/BirjuVachhani/box_transform/issues
documentation: https://docs.page/BirjuVachhani/box_transform

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  box_transform: ^0.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
