name: box_transform
description: A pure dart implementation for advanced resizing of rect in UI.

version: 0.1.0

repository: https://github.com/BirjuVachhani/box_transform
homepage: https://github.com/BirjuVachhani/box_transform
issue_tracker: https://github.com/BirjuVachhani/box_transform/issues
documentation: https://docs.page/BirjuVachhani/box_transform

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
  coverage: ^1.6.3