name: Build PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Get PR number
        id: pr_number
        run: echo "number=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_OUTPUT
      - name: Install Melos
        run: flutter pub global activate melos
      - name: Run melos
        run: melos bootstrap
      - name: Get Dependencies
        run: melos deps
      - name: Build Example
        run: flutter build web --release
      - name: Clone deployment repo
        run: git clone --single-branch "https://${{ secrets.PAT }}@github.com/hyper-designed/box_transform_deployments.git" "clone_dir"
      - name: Remove old build
        run: rm -rf clone_dir/pr/${{ steps.pr_number.outputs.number }}
      - name: Create new build
        run: mkdir -p clone_dir/pr/${{ steps.pr_number.outputs.number }}
      - name: Move build to deployment repo
        run: mv build/web/* clone_dir/pr/${{ steps.pr_number.outputs.number }}
      - name: Push build commit
        run: |
          cd clone_dir
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Build PR ${{ steps.pr_number.outputs.number }}"
          git pull --rebase
          git push
      - name: Update PR with demo links
        uses: thollander/actions-comment-pull-request@main
        with:
          message: "Demo: https://demo.boxtransform.hyperdesigned.com/pr/${{ steps.pr_number.outputs.number }}/"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}