name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install Melos
        run: flutter pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Check formatting
        run: melos check-format
      - name: Analyze
        run: melos analyze
